#Enter your  vvvv license key here
licensekey: "INSERT YOUR LICENSE KEY HERE"
StingerRadius: 1600.0
LaserRadius: 144.0
TrackerRadius: 68
Mark50Protection: 3
Mark34Protection: 5
# Stocks gui
#00 01 02 03 04 05 06 07 08
#09 10 11 12 13 14 15 16 17
#18 19 10 11 12 13 14 15 16
Peescoin: 11
RLN: 13
Potatocoin: 15
